language: android

jdk:
 - oraclejdk8

android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.2
    - android-23
    - extra-android-support
    - extra-google-google_play_services
    
  licenses:
    - '.+'

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle
